### ISSUE TITLE
Cannot change text because of invisible label

### ISSUE THREAD

**Issue by gbeumer** [CastleCSS/castlecss-forms#46] opened 2018-01-23 13:33 UTC

**Comment by pascalalferink** [comment] 2018-02-16 08:16
Further explanation of the issue:
When a value is entered in an input-field, the label disappears with opacity: 0. The issue is that the label is still clickable. So when you try to select the value of the input-field, it is not possible because the label is being selected.  

In the screenshot below you can see the issue: you can't select the value where there is a label.

![image](https://user-images.githubusercontent.com/13336728/36297796-f59dbf98-12f4-11e8-8937-f8396217e4cd.png)

One

**Comment by pascalalferink** [comment] 2018-02-16 08:27
this issue is dealt with in pull-request:   https://github.com/CastleCSS/castlecss-forms/pull/47

**Comment by dariusrosendahl** [comment] 2018-02-20 11:48
Released in https://github.com/CastleCSS/castlecss-forms/releases/tag/v1.0.12

**Closed by dariusrosendahl** 2018-02-20 11:48 UTC
